version: '3'
services:
  mysql:
    build: ./mysql
    restart: always
    hostname: mysql
    container_name: mysql
    volumes:
      - './mysql/volume:/var/lib/mysql'
      - './mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      MYSQL_ROOT_PASSWORD: ThisisCS50
      MYSQL_DATABASE: pictionary
    tty: true
    networks:
      pictionary_net:
        ipv4_address: 10.10.0.5
    extra_hosts:
      - 'nginx: 10.10.0.2'
      - 'springboot: 10.10.0.4'
      - 'mysql: 10.10.0.5'
  npmbuld:
    build: ./npmbuild
    hostname: npmbuild
    container_name: npmbuild
    ports:
      - '3000:3000'
    volumes:
      - './npmbuild/volume:/tmp/build'
    tty: true
    stdin_open: true
    networks:
      pictionary_net:
        ipv4_address: 10.10.0.3
    extra_hosts:
      - 'nginx: 10.10.0.2'
      - 'springboot: 10.10.0.4'
      - 'mysql: 10.10.0.5'
  springboot:
    build: ./springboot
    hostname: springboot
    restart: always
    container_name: springboot
    volumes:
      - './springboot/volume:/tmp'
    tty: true
    stdin_open: true
    networks:
      pictionary_net:
        ipv4_address: 10.10.0.4
    extra_hosts:
      - 'nginx: 10.10.0.2'
      - 'springboot: 10.10.0.4'
      - 'mysql: 10.10.0.5'
  nginx:
    build: ./nginx
    hostname: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './npmbuild/volume:/var/www/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    tty: true
    stdin_open: true
    networks:
      pictionary_net:
        ipv4_address: 10.10.0.2
    extra_hosts:
      - 'nginx: 10.10.0.2'
      - 'springboot: 10.10.0.4'
      - 'mysql: 10.10.0.5'
# Define default network.
networks:
  pictionary_net:
    name: pictionary
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24    #/24の場合は一番後ろの0の部分を0～255(実質は2～254)の範囲内で設定可能
