version: '3'
services:
  mysql:
    build: ./mysql
    image: ${DOCKER_USER}/mysql:${CIRCLE_SHA1}
    restart: always
    volumes:
      - './mysql/volume:/var/lib/mysql'
      - './mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      MYSQL_ROOT_PASSWORD: ThisisCS50
      MYSQL_DATABASE: pictionary
  springboot:
    build: ./springboot
    image: ${DOCKER_USER}/springboot:${CIRCLE_SHA1}
    restart: always
  react:
    build: ./react
    image: ${DOCKER_USER}/react:${CIRCLE_SHA1}
    stdin_open: true
  nginx:
    build: ./nginx
    image: ${DOCKER_USER}/nginx:${CIRCLE_SHA1}
    ports:
      - '80:80'
      - '443:443'
